from app.models.user import User
from app.models.student import Student
from app.models.instructor import Instructor
from app.models.administrator import Administrator
from app.models.data_analyst import DataAnalyst
from app.models.university import University
from app.models.course import Course
from app.models.topic import Topic
from app.models.course_topic import CourseTopic
from app.models.enrollment import Enrollment
from app.models.teaching import Teaching
from app.models.course_content import CourseContent
from app.models.statistics import Statistics
from app.models.student_statistics import StudentStatistics
from app.models.instructor_statistics import InstructorStatistics